# Generated by Django 5.2 on 2025-05-07 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_initial'),
        ('core', '0002_initial'),
        ('waste_collectors', '0001_initial'),
        ('waste_source_group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waste_weight', models.FloatField()),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commoditymater')),
                ('waste_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_source_group.mastersource')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commoditygroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WastePickUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_date', models.DateField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='waste_pickup')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_collectors.collector')),
                ('waste_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_generators.wastesource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WasteSourceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_email', models.EmailField(max_length=254, null=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.address')),
                ('waste_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_source_group.wastegeneratorgroup')),
                ('waste_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_source_group.mastersource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WasteSourceSpecificationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('waste_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_generators.wastesourcemaster')),
            ],
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_email', models.EmailField(max_length=254, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('Waste_generator_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waste_source_group.wastegeneratorgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('waste_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waste_generators.wastesourcemaster')),
                ('waste_source_specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waste_generators.wastesourcespecificationmaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
