# Generated by Django 5.2 on 2025-05-07 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
        ('core', '0002_initial'),
        ('waste_generators', '0001_initial'),
        ('waste_source_group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_generators.wastesourcemaster'),
        ),
        migrations.AddField(
            model_name='audit',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_location', to='waste_source_group.mastersource'),
        ),
        migrations.AddField(
            model_name='auditcommoditi',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_commoditi', to='audits.audit'),
        ),
        migrations.AddField(
            model_name='auditcommoditi',
            name='commodity_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commoditygroup'),
        ),
        migrations.AddField(
            model_name='auditcompliance',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_compliance', to='audits.audit'),
        ),
        migrations.AddField(
            model_name='noncompliancenotice',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='audits.audit'),
        ),
        migrations.AddField(
            model_name='official',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='official',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offical_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audit',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_offical', to='audits.official'),
        ),
        migrations.AddField(
            model_name='audit',
            name='waiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audits.waiver'),
        ),
    ]
