# Generated by Django 5.2 on 2025-05-07 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditymater',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commodity_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commoditymater',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.commoditygroup', verbose_name='Commodity Group'),
        ),
        migrations.AddField(
            model_name='commoditymater',
            name='measuring_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.measuringunitmaster'),
        ),
    ]
