# Generated by Django 5.2 on 2025-05-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodities', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcommodity',
            name='commoditie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commoditymater'),
        ),
    ]
